// Turkish interface text: the English text (or an id) maps to its Turkish. A missing entry shows the English.
// Rules: no suffix after a {placeholder} (rephrase instead), one string for the plural, the same {placeholders} and HTML tags as the English.
export default {
  // ——— index.html: what the example chips type into the composer (data-t-fill) must be something js/core.js parseLocal understands ———
  '85.4': '85,4',
  '8200 steps': '8200 adım',
  'water 2 glasses': '2 bardak su',
  '2 coffees': '2 kahve',
  workout: 'antrenman',
  '2 slices of pizza and a beer': '2 dilim pizza ve bir bira',

  // ——— index.html: static text ———
  'Pickle: good things take time. A weight-loss tracker: a meal plan, a photo and text food log, and daily tracking. Entries, photos and settings are stored on this device.': 'Pickle: güzel şeyler zaman alır. Bir kilo verme takipçisi: yemek planı, fotoğraflı ve yazılı yemek günlüğü ve günlük takip. Kayıtlar, fotoğraflar ve ayarlar bu cihazda saklanır.',
  'Things you can type': 'Yazabileceklerin',
  Examples: 'Örnekler',
  'Weight: 85.4': 'Kilo: 85,4',
  'Water 2 glasses': 'Su 2 bardak',
  'What you ate, or your weight': 'Ne yedin ya da kaç kilosun',
  'What did you eat?': 'Ne yedin?',
  Send: 'Gönder',
  Sections: 'Bölümler',

  // ——— js/ai.js: error messages, their short labels, and the waiting note ———
  'No API key. Add one in Settings.': 'API anahtarı yok. Ayarlar’dan bir tane ekle.',
  'The API key was rejected. Check it in Settings.': 'API anahtarı reddedildi. Ayarlar’dan kontrol et.',
  'No internet.': 'İnternet yok.',
  'Could not reach the server. If you are online, this provider may not allow calls from a browser.': 'Sunucuya ulaşılamadı. İnternetin varsa bu sağlayıcı tarayıcıdan gelen isteklere izin vermiyor olabilir.',
  'The provider took too long to answer.': 'Sağlayıcı çok geç yanıt verdi.',
  'The answer was cut off before it was complete. Try again, or add a short note.': 'Yanıt tamamlanmadan kesildi. Tekrar dene ya da kısa bir not ekle.',
  'Too many requests or the quota is used up.': 'Çok fazla istek gönderildi ya da kota doldu.',
  'This model has no quota on your plan. Pick another model in Settings.': 'Planında bu model için kota yok. Ayarlar’dan başka bir model seç.',
  'The provider says the account has no credit. Add credit or pick another provider in Settings.': 'Sağlayıcı hesapta bakiye olmadığını söylüyor. Bakiye ekle ya da Ayarlar’dan başka bir sağlayıcı seç.',
  'The provider wants billing enabled on this account before it answers. Enable it with the provider or pick another one in Settings.': 'Sağlayıcı, yanıt vermeden önce bu hesapta faturalandırmanın açılmasını istiyor. Sağlayıcıda etkinleştir ya da Ayarlar’dan başka bir sağlayıcı seç.',
  'This model does not accept photos. Pick a model with image support in Settings.': 'Bu model fotoğraf kabul etmiyor. Ayarlar’dan görsel destekleyen bir model seç.',
  'Model not found. Check the model name in Settings.': 'Model bulunamadı. Model adını Ayarlar’dan kontrol et.',
  'The provider is busy right now.': 'Sağlayıcı şu an yoğun.',
  'The request was rejected.': 'İstek reddedildi.',
  'The model could not interpret this input. Add a short note and try again.': 'Model bu girdiyi yorumlayamadı. Kısa bir not ekleyip tekrar dene.',
  'The request failed.': 'İstek başarısız oldu.',
  'no api key': 'API anahtarı yok',
  'the api key was rejected': 'API anahtarı reddedildi',
  'no internet': 'internet yok',
  'could not reach the server': 'sunucuya ulaşılamadı',
  'the provider took too long to answer': 'sağlayıcı çok geç yanıt verdi',
  'the answer was cut off before it was complete': 'yanıt tamamlanmadan kesildi',
  'too many requests or the quota is used up': 'çok fazla istek ya da kota doldu',
  'this model has no quota on your plan': 'planında bu model için kota yok',
  'the provider says the account has no credit': 'sağlayıcı hesapta bakiye yok diyor',
  'the provider wants billing enabled on this account before it answers': 'sağlayıcı faturalandırmanın açılmasını istiyor',
  'this model does not accept photos': 'bu model fotoğraf kabul etmiyor',
  'model not found': 'model bulunamadı',
  'the provider is busy right now': 'sağlayıcı şu an yoğun',
  'the request was rejected': 'istek reddedildi',
  'the model could not interpret this input': 'model bu girdiyi yorumlayamadı',
  'the request failed': 'istek başarısız oldu',
  ' The entry is waiting; tap “Analyse” to try again.': ' Kayıt bekliyor; tekrar denemek için “Analiz et” düğmesine dokun.',

  // ——— js/backup.js ———
  'This is not a Pickle backup': 'Bu bir Pickle yedeği değil',
  'This backup has no valid version number, so it cannot be restored': 'Bu yedekte geçerli bir sürüm numarası yok, bu yüzden geri yüklenemez',
  'This backup is from a newer version of Pickle. Update the app first': 'Bu yedek Pickle’ın daha yeni bir sürümünden. Önce uygulamayı güncelle',

  // ——— js/core.js ———
  '{kcal} kcal above the budget': '{kcal} kcal bütçenin üstünde',
  '{kcal} kcal under the {min} minimum': '{min} minimumunun {kcal} kcal altında',
  '{kcal} kcal above the budget, within the {pct}% margin': '{kcal} kcal bütçenin üstünde, %{pct} payın içinde',
  'protein {gap} g short of your minimum': 'protein minimumunun {gap} g altında',
  '{n} off-plan entry|{n} off-plan entries': '{n} plan dışı kayıt',
  // The five daily goals
  'Weigh-in': 'Tartım',
  Calories: 'Kalori',
  Protein: 'Protein',
  Steps: 'Adım',
  Water: 'Su',
  // The week's verdicts
  'Strong week': 'Güçlü hafta',
  'Every day on plan. Beautifully steady.': 'Her gün planda. Harika bir düzen.',
  'Solid week': 'Sağlam hafta',
  'Only one day off. Growing nicely.': 'Yalnızca bir gün planın dışında kaldı. Güzel ilerliyorsun.',
  'Steady week': 'Dengeli hafta',
  'Most days on plan. A good rhythm to build on.': 'Günlerin çoğu planda. Üzerine kurulacak güzel bir ritim.',
  'Rough patch': 'Zor bir dönem',
  'Less than half of the week landed. Look at which days slipped and plan those first. Next week is a fresh start.': 'Haftanın yarısından azı planda geçti. Hangi günlerin kaydığına bak ve önce onları planla. Gelecek hafta yeni bir başlangıç.',
  'Time to reset': 'Yeniden başlama zamanı',
  'Few days on plan this week. One day at a time, begin again on Monday.': 'Bu hafta planda az gün oldu. Gün gün ilerle, Pazartesi yeniden başla.',
  // The day's verdict
  'In progress': 'Devam ediyor',
  'Not much logged': 'Az kayıt var',
  'In line': 'Yolunda',
  'Under budget': 'Bütçenin altında',
  'A little above': 'Biraz üstünde',
  'A bigger day': 'Yüklü bir gün',
  'Only {kcal} kcal logged, not enough to judge the day yet.': 'Yalnızca {kcal} kcal kaydedildi, günü değerlendirmek için henüz yetmez.',
  '{kcal} kcal left for today.': 'Bugün için {kcal} kcal kaldı.',
  'The budget for today is used up.': 'Bugünün bütçesi doldu.',
  '{kcal} kcal above budget. One day does not change the trend.': '{kcal} kcal bütçenin üstünde. Tek bir gün gidişatı değiştirmez.',
  '{kcal} kcal above budget: about {kg} kg. One day does not change the trend.': '{kcal} kcal bütçenin üstünde: yaklaşık {kg} kg. Tek bir gün gidişatı değiştirmez.',
  '{kcal} kcal above budget: about {kg} kg, {days} days of the schedule. One day does not change the trend.': '{kcal} kcal bütçenin üstünde: yaklaşık {kg} kg, programın {days} günü. Tek bir gün gidişatı değiştirmez.',
  '{kcal} kcal above budget: about {kg} kg, all of what the day was meant to lose. One day does not change the trend.': '{kcal} kcal bütçenin üstünde: yaklaşık {kg} kg, günün vermesi gereken kilonun tamamı. Tek bir gün gidişatı değiştirmez.',
  '{kcal} kcal above budget: about {kg} kg, {pct}% of what the day was meant to lose. One day does not change the trend.': '{kcal} kcal bütçenin üstünde: yaklaşık {kg} kg, günün vermesi gereken kilonun %{pct} kadarı. Tek bir gün gidişatı değiştirmez.',
  '{kcal} kcal under budget; check that everything is logged.': '{kcal} kcal bütçenin altında; her şeyin kaydedildiğinden emin ol.',
  '{kcal} kcal under budget.': '{kcal} kcal bütçenin altında.',
  'On budget.': 'Bütçede.',
  'Protein {gap} g short of your minimum.': 'Protein minimumunun {gap} g altında.',
  '{n} off-plan entry.|{n} off-plan entries.': '{n} plan dışı kayıt.',
  // The calorie meter's text
  'Ended {n} above': 'Bütçenin {n} üstünde bitti',
  'Well above budget': 'Bütçenin çok üstünde',
  'A little above budget': 'Bütçenin biraz üstünde',
  'Nothing logged': 'Kayıt yok',
  'Ended on budget': 'Bütçede bitti',
  'Ended {n} under': 'Bütçenin {n} altında bitti',
  'Budget used': 'Bütçe kullanıldı',
  'Budget used early': 'Bütçe erken bitti',
  'Nothing eaten yet': 'Henüz bir şey yenmedi',
  '{n} above plan pace': 'Plan temposunun {n} üstünde',
  '{n} under plan pace': 'Plan temposunun {n} altında',
  'On plan pace': 'Plan temposunda',
  // Titles of generated entries
  'Weight {kg} kg': 'Kilo {kg} kg',
  '{steps} steps': '{steps} adım',
  Photo: 'Fotoğraf',

  // ——— js/plan.js: foods ———
  'Boiled egg': 'Haşlanmış yumurta',
  'Low-fat white cheese': 'Az yağlı beyaz peynir',
  'Cucumber, tomato, greens': 'Salatalık, domates, yeşillik',
  Olives: 'Zeytin',
  'Whole-wheat or rye bread': 'Tam buğday veya çavdar ekmeği',
  'Olive oil': 'Zeytinyağı',
  'Boiled potato (cooled)': 'Haşlanmış patates (soğutulmuş)',
  'Tuna in water, drained': 'Suda ton balığı, süzülmüş',
  'Plain skyr': 'Sade skyr',
  'Unsweetened muesli': 'Şekersiz müsli',
  'Soy flakes': 'Soya gevreği',
  Banana: 'Muz',
  'Mixed berries': 'Karışık orman meyveleri',
  'Peach (or a handful of cherries or grapes)': 'Şeftali (ya da bir avuç kiraz veya üzüm)',
  Walnuts: 'Ceviz',
  Crispbread: 'Gevrek ekmek',
  Hummus: 'Humus',
  'Raw vegetables (pepper, carrot, cucumber)': 'Çiğ sebzeler (biber, havuç, salatalık)',
  'Kefir or plain ayran': 'Kefir veya sade ayran',
  'Raw almonds or hazelnuts': 'Çiğ badem veya fındık',
  'Cottage cheese': 'Lor peyniri',
  'Chicken breast (raw weight)': 'Tavuk göğsü (çiğ ağırlık)',
  'Lean mince, max 10% fat (raw)': 'Yağsız kıyma, en fazla %10 yağlı (çiğ)',
  'Lean red meat (raw weight)': 'Yağsız kırmızı et (çiğ ağırlık)',
  'Salmon (raw weight)': 'Somon (çiğ ağırlık)',
  'Oven vegetables (a frozen mix is fine)': 'Fırın sebze (dondurulmuş karışık olur)',
  'Cooked bulgur': 'Pişmiş bulgur',
  'Cooked green lentils or chickpeas': 'Pişmiş yeşil mercimek veya nohut',
  // js/plan.js: meal templates and amounts
  'Egg and cheese plate': 'Yumurta ve peynir tabağı',
  '2 eggs': '2 yumurta',
  'large bowl': 'büyük kase',
  '5 olives': '5 zeytin',
  '1 slice': '1 dilim',
  '1 tsp': '1 çay kaşığı',
  'Potato salad (no bread)': 'Patates salatası (ekmeksiz)',
  '1 medium': '1 orta boy',
  'Tuna salad': 'Ton balıklı salata',
  '1 can': '1 kutu',
  '1 egg': '1 yumurta',
  'Vegetable omelette': 'Sebzeli omlet',
  '3 eggs': '3 yumurta',
  'Skyr bowl with berries': 'Orman meyveli skyr kasesi',
  '3 tbsp': '3 yemek kaşığı',
  '1 tbsp': '1 yemek kaşığı',
  '1 handful': '1 avuç',
  'Skyr bowl with banana': 'Muzlu skyr kasesi',
  half: 'yarım',
  'Skyr bowl with peach': 'Şeftalili skyr kasesi',
  '1 peach': '1 şeftali',
  'Walnuts and fruit': 'Ceviz ve meyve',
  '5 walnuts': '5 ceviz',
  '1 portion': '1 porsiyon',
  'Crispbread and hummus': 'Gevrek ekmek ve humus',
  '2 slices': '2 dilim',
  '2 tbsp': '2 yemek kaşığı',
  'Kefir and almonds': 'Kefir ve badem',
  '1 glass': '1 bardak',
  '12 almonds': '12 badem',
  'Cottage cheese and raw vegetables': 'Lor peyniri ve çiğ sebze',
  'Chicken and oven vegetables': 'Tavuk ve fırın sebze',
  '4 tbsp': '4 yemek kaşığı',
  '2 tsp': '2 çay kaşığı',
  'Meatballs and salad': 'Köfte ve salata',
  'Red meat and oven vegetables': 'Kırmızı et ve fırın sebze',
  'Salmon and oven vegetables': 'Somon ve fırın sebze',
  'Lentils and chicken': 'Mercimek ve tavuk',
  'Pre-workout banana': 'Antrenman öncesi muz',
  '1 banana': '1 muz',
  'Post-workout skyr': 'Antrenman sonrası skyr',
  // js/plan.js: slots and drinks
  Lunch: 'Öğle yemeği',
  'Snack 1': '1. ara öğün',
  'Snack 2': '2. ara öğün',
  Dinner: 'Akşam yemeği',
  Late: 'Geç saat',
  Morning: 'Sabah',
  Workout: 'Antrenman',
  'Beer 0.33 l': 'Bira 0,33 l',
  'Beer 0.5 l': 'Bira 0,5 l',
  // js/plan.js: the plan's rules
  'At least 2 to 2.5 litres of water a day.': 'Günde en az 2 ila 2,5 litre su.',
  '{steps} steps a day. With a desk job this is the cheapest part of the deficit.': 'Günde {steps} adım. Masa başı bir işte bu, kalori açığının en ucuz kısmı.',
  'Meat, chicken and fish are weighed raw.': 'Et, tavuk ve balık çiğ tartılır.',
  'Cooking and salad oil is measured: 1 tsp of olive oil is about 45 kcal.': 'Yemek ve salata yağı ölçülür: 1 çay kaşığı zeytinyağı yaklaşık 45 kcal.',
  'Nuts are raw and unsalted, 20 to 25 g, and weighed. Walnuts, almonds, hazelnuts and peanuts follow the same rule.': 'Kuruyemişler çiğ ve tuzsuz olur, 20 ila 25 g tartılır. Ceviz, badem, fındık ve yer fıstığı aynı kurala uyar.',
  'Two portions of fruit a day. Total calories decide the outcome, not the fruit itself.': 'Günde iki porsiyon meyve. Sonucu toplam kalori belirler, meyvenin kendisi değil.',
  'If you add potato to the salad, skip the bread that day. Boiled and cooled potato keeps you full longer.': 'Salataya patates eklersen o gün ekmeği atla. Haşlanıp soğutulmuş patates seni daha uzun süre tok tutar.',
  'After 20:00, herbal tea. If you are very hungry or short on protein, 150 g of plain skyr.': 'Saat 20:00’den sonra bitki çayı. Çok açsan ya da proteinin eksikse 150 g sade skyr.',
  'One flexible dinner (eating out or off plan), around 700 kcal.': 'Bir esnek akşam yemeği (dışarıda ya da plan dışı), yaklaşık 700 kcal.',
  'One beer (0.33 l) or one small dessert up to {kcal} kcal. No crisps, peanuts or fried food with it.': 'Bir bira (0,33 l) ya da en fazla {kcal} kcal olan küçük bir tatlı. Yanında cips, yer fıstığı ya da kızartma olmasın.',
  'Sugary drinks: cola, soda, fruit juice.': 'Şekerli içecekler: kola, gazoz, meyve suyu.',
  'Deep-fried food, including fries.': 'Kızartmalar, patates kızartması dahil.',
  'Crisps and salted, roasted nuts.': 'Cips ve tuzlu, kavrulmuş kuruyemiş.',
  'Pastries: simit, poğaça, börek, croissant, pretzel.': 'Hamur işleri: simit, poğaça, börek, kruvasan, pretzel.',
  'White bread, toast bread, lavash.': 'Beyaz ekmek, tost ekmeği, lavaş.',
  'Three workouts a week: spinning, or kettlebell (swing, halo) plus core.': 'Haftada üç antrenman: spinning ya da kettlebell (swing, halo) ve core çalışması.',
  'At least two fixed kettlebell days. Resistance training is what protects muscle in a deficit.': 'En az iki sabit kettlebell günü. Kalori açığında kası koruyan şey direnç antrenmanıdır.',
  'Workout days are {kcal} kcal: add a banana before and 150 g of skyr after.': 'Antrenman günlerinde bütçe {kcal} kcal: öncesine bir muz, sonrasına 150 g skyr ekle.',
  'Weigh in every morning under the same conditions. Read the 7-day average, not a single day.': 'Her sabah aynı koşullarda tartıl. Tek bir güne değil, 7 günlük ortalamaya bak.',
  'If the average sits more than 0.7 kg above the line two weeks in a row: cut 100 kcal or add 2,000 steps.': 'Ortalama art arda iki hafta çizginin 0,7 kg’dan fazla üstünde kalırsa: 100 kcal azalt ya da 2.000 adım ekle.',
  'Do not go below {kcal} kcal.': 'Alt sınır {kcal} kcal: bunun altına inme.',
  'On reaching {kg} kg, raise calories to maintenance gradually over 2 to 3 weeks.': 'Hedef {kg} kg: ulaşınca kaloriyi 2 ila 3 hafta içinde yavaş yavaş idame seviyesine çıkar.',
  // js/plan.js: the week
  Monday: 'Pazartesi',
  Tuesday: 'Salı',
  Wednesday: 'Çarşamba',
  Thursday: 'Perşembe',
  Friday: 'Cuma',
  Saturday: 'Cumartesi',
  'Salmon or the flexible dinner': 'Somon ya da esnek akşam yemeği',
  Sunday: 'Pazar',

  // ——— js/views.js: week letters ———
  Mo: 'Pt',
  Tu: 'Sa',
  We: 'Ça',
  Th: 'Pe',
  Fr: 'Cu',
  Sa: 'Ct',
  Su: 'Pz',

  // ——— js/views.js: header and weight summary ———
  Settings: 'Ayarlar',
  '{toLose} to lose by {date}, about {pace} kg a week.': '{date} tarihine kadar {toLose} vermen gerek, haftada yaklaşık {pace} kg.',
  'Starts tomorrow': 'Yarın başlıyor',
  'Starts {day}': '{day} başlıyor',
  'Starts {date}': '{date} başlıyor',
  'No weigh-in yet': 'Henüz tartım yok',
  '{toLose} to lose': 'Verilecek: {toLose}',
  '{kg} kg {dir}': '{kg} kg {dir}',
  up: 'arttı',
  down: 'azaldı',
  'You reached {kg} kg': 'Hedefe ulaştın: {kg} kg',
  '{moved} since {date}.': '{date} tarihinden beri {moved}.',
  'Goal reached': 'Hedefe ulaşıldı',
  '{kg} kg from the goal': 'Hedefe {kg} kg var',
  'On schedule': 'Programda',
  '{kg} kg ahead of schedule': 'Programın {kg} kg önünde',
  '{kg} kg behind schedule': 'Programın {kg} kg gerisinde',
  '{moved}, {toLose} to go, {days} left.': '{moved}, {toLose} kaldı, geriye {days} var.',
  '{moved}, {toLose} to go.': '{moved}, {toLose} kaldı.',
  '{toLose} to go': '{toLose} kaldı',
  '{kg} kg ahead': '{kg} kg önde',
  '{kg} kg behind': '{kg} kg geride',

  // ——— js/views.js: the week strip ———
  'on plan': 'planda',
  'in progress': 'devam ediyor',
  'over the budget': 'bütçenin üstünde',
  'well over the budget': 'bütçenin çok üstünde',
  'under the minimum': 'minimumun altında',
  'nothing logged': 'kayıt yok',
  'still to come': 'henüz gelmedi',
  'before the plan started': 'plan başlamadan önce',
  '{date}: all goals done': '{date}: tüm hedefler tamam',
  '{date}: {status}': '{date}: {status}',
  '<b>{days}</b> on plan in a row': '<b>{days}</b> art arda planda',
  'A day on plan starts a new run': 'Planda geçen bir gün yeni bir seri başlatır',
  'All five goals': 'Beş hedefin hepsi',
  '{done} of {total} goals so far': 'Şu ana kadar hedefler: {done}/{total}',
  '{done} of {total} goals': 'Hedefler: {done}/{total}',
  'Days of the week': 'Haftanın günleri',
  'Previous week': 'Önceki hafta',
  'Next week': 'Sonraki hafta',
  '{goal}: {state}': '{goal}: {state}',
  done: 'tamam',
  open: 'açık',

  // ——— js/views.js: Today, the calorie budget ———
  'All planned meals are due': 'Planlanan tüm öğünlerin vakti geldi',
  'Plan by now <b>{kcal}</b>': 'Şimdiye kadar plan <b>{kcal}</b>',
  'Plan starts at {time}': 'Plan başlangıcı: {time}',
  'kcal eaten of {target}': 'kcal yendi, hedef {target}',
  'kcal left of {target}': 'kcal kaldı, hedef {target}',
  'kcal above budget': 'kcal bütçenin üstünde',
  'Calorie budget: {eaten} of {target} kcal eaten.': 'Kalori bütçesi: yenen {eaten} kcal, hedef {target} kcal.',
  'Calorie budget: {eaten} of {target} kcal eaten, {n} left.': 'Kalori bütçesi: yenen {eaten} kcal, hedef {target} kcal, kalan {n}.',
  'Calorie budget: {eaten} of {target} kcal eaten, {n} above.': 'Kalori bütçesi: yenen {eaten} kcal, hedef {target} kcal, aşan {n}.',
  'The plan has {n} by now.': 'Plana göre şimdiye kadar {n} olmalı.',
  'Calorie budget': 'Kalori bütçesi',
  '<b>{kcal}</b> eaten': '<b>{kcal}</b> yendi',

  // ——— js/views.js: Today, the tiles ———
  'avg {kg} · {status}': 'ort. {kg} · {status}',
  'Today’s weigh-in {kg} kg. Change': 'Bugünkü tartım {kg} kg. Değiştir',
  'Enter today’s weigh-in': 'Bugünkü tartımı gir',
  'Weight. {head}. {line} {action}': 'Kilo. {head}. {line} {action}',
  Weight: 'Kilo',
  'tap to weigh in': 'tartım için dokun',
  'Weigh-in on this day: {kg} kg. Change': 'Bu günün tartımı: {kg} kg. Değiştir',
  'Weigh-in on this day: none. Add': 'Bu günün tartımı: yok. Ekle',
  'tap to add': 'eklemek için dokun',
  'cup|cups': 'fincan',
  '{n} cup|{n} cups': '{n} fincan',
  'Coffee: {cups} today, {n} this week. Add one': 'Kahve: bugün {cups}, bu hafta {n}. Bir tane ekle',
  'Coffee: {cups} on this day, {n} this week. Add one': 'Kahve: bu gün {cups}, bu hafta {n}. Bir tane ekle',
  'Coffee: {cups} on this day, {n} that week. Add one': 'Kahve: o gün {cups}, o hafta {n}. Bir tane ekle',
  'The day at a glance': 'Günün özeti',
  'Protein: {p} of {goal} g': 'Protein: {p} / {goal} g',
  'Enough for today': 'Bugün için yeterli',
  '{n} g to go': '{n} g kaldı',
  'Steps, water and coffee': 'Adım, su ve kahve',
  'Steps: {n} of {goal}. Enter': 'Adım: {n} / {goal}. Gir',
  'Steps: none of {goal}. Enter': 'Adım: henüz yok, hedef {goal}. Gir',
  '{n} to go': '{n} kaldı',
  'Water: {n} of {goal} litres. Add a glass': 'Su: {n} / {goal} litre. Bir bardak ekle',
  '{n} glass to go|{n} glasses to go': '{n} bardak kaldı',
  'Remove a glass of water': 'Bir bardak suyu çıkar',
  Coffee: 'Kahve',
  '{n} this week, {prev} last week': 'Bu hafta {n}, geçen hafta {prev}',
  '{n} this week': 'Bu hafta {n}',
  '{n} that week': 'O hafta {n}',
  'Remove one coffee': 'Bir kahveyi çıkar',

  // ——— js/views.js: Today, meals ———
  Analysing: 'Analiz ediliyor',
  'Analysis failed': 'Analiz başarısız',
  'Waiting for analysis': 'Analiz bekleniyor',
  'Workout extras': 'Antrenman ekstraları',
  'Banana before, skyr after': 'Öncesinde muz, sonrasında skyr',
  'Herbal tea; skyr if very hungry': 'Bitki çayı; çok açsan skyr',
  'After {time}': '{time} sonrası',
  'Done:': 'Tamamlanan:',
  'Waiting:': 'Bekleyen:',
  '{slot}: other options': '{slot}: diğer seçenekler',
  'Next:': 'Sıradaki:',
  'not logged yet': 'henüz kaydedilmedi',
  '{meal}, {kcal} kcal, the lightest option': '{meal}, {kcal} kcal, en hafif seçenek',
  '{meal}, {kcal} kcal': '{meal}, {kcal} kcal',
  'Log {meal}': 'Kaydet: {meal}',
  'meal.log': 'Kaydet', // the "Log" button next to a meal
  '{slot}: choose a meal': '{slot}: bir öğün seç',
  'Today’s meals': 'Bugünün öğünleri',
  Meals: 'Öğünler',
  '{n} of {total}': '{n}/{total}',
  'Workout day: budget {kcal} kcal, banana and skyr added': 'Antrenman günü: bütçe {kcal} kcal, muz ve skyr eklendi',
  'Workout day': 'Antrenman günü',
  Meal: 'Öğün',
  Close: 'Kapat',
  'Tap what you are having.': 'Ne yiyorsan ona dokun.',
  'Tap what you had.': 'Ne yediysen ona dokun.',
  suggested: 'önerilen',
  '{n} g protein': '{n} g protein',
  'Something that is not on the plan:': 'Planda olmayan bir şey:',
  'Take a photo': 'Fotoğraf çek',
  'Type it': 'Yaz',
  Supplements: 'Takviyeler',
  '{n} over': '{n} fazla',
  Used: 'Kullanıldı',
  '{n} left': '{n} kaldı',
  'This week’s extras': 'Bu haftanın ekstraları',
  'Beer or small dessert': 'Bira veya küçük tatlı',
  'Flexible dinner': 'Esnek akşam yemeği',
  'Off-plan entries': 'Plan dışı kayıtlar',

  // ——— js/views.js: Today, the coach and the AI note ———
  'A bigger day today.': 'Bugün biraz yüklü bir gün.',
  'One day doesn’t change the trend; the weekly average is what counts. Tomorrow is a normal plan day, and there is no need to skip a meal to make up for it.': 'Tek bir gün gidişatı değiştirmez; önemli olan haftalık ortalama. Yarın normal bir plan günü, telafi etmek için öğün atlamana gerek yok.',
  'A little above today.': 'Bugün biraz fazla.',
  'That’s fine. Carry on with the plan as usual tomorrow.': 'Sorun değil. Yarın planına her zamanki gibi devam et.',
  'A fresh day.': 'Yeni bir gün.',
  'First up: {meal} at {time}.': 'İlk sırada: {meal}, saat {time}.',
  'Meals done.': 'Öğünler tamam.',
  'Protein is {n} g short; 150 g of plain skyr closes the gap and fits the budget.': 'Protein {n} g eksik; 150 g sade skyr açığı kapatır ve bütçeye uyar.',
  'You’re on track.': 'Yolundasın.',
  'Next: {meal} at {time}, which also helps with protein.': 'Sıradaki: {meal}, saat {time}; proteine de katkı sağlar.',
  'Next: {meal} at {time}.': 'Sıradaki: {meal}, saat {time}.',
  'Next: {meal}, which also helps with protein.': 'Sıradaki: {meal}; proteine de katkı sağlar.',
  'Next: {meal}.': 'Sıradaki: {meal}.',
  'Protein is {n} g short.': 'Protein {n} g eksik.',
  'All meals in, on budget.': 'Tüm öğünler girildi, bütçedesin.',
  'Nicely done.': 'Güzel iş.',
  'AI note': 'Yapay zekâ notu',
  'Writing a note…': 'Not yazılıyor…',
  'AI note, {time}.': 'Yapay zekâ notu, {time}.',
  'How am I doing so far?': 'Şu ana kadar nasıl gidiyorum?',
  'Ask again': 'Tekrar sor',
  'Update the note': 'Notu güncelle',

  // ——— js/views.js: getting started ———
  'Enter your first weigh-in': 'İlk tartımını gir',
  'Tap the Weight tile below. Progress and forecasts are calculated from your weigh-ins.': 'Aşağıdaki Kilo kutusuna dokun. İlerleme ve tahminler tartımlarından hesaplanır.',
  'Log your first meal': 'İlk öğününü kaydet',
  'Tap “Log” next to the suggested meal under Today’s meals. No key needed.': 'Bugünün öğünleri altında önerilen öğünün yanındaki “Kaydet” düğmesine dokun. Anahtar gerekmez.',
  'Add a key for photo analysis': 'Fotoğraf analizi için anahtar ekle',
  'Gemini’s free tier is enough. Plan meals work without a key.': 'Gemini’nin ücretsiz katmanı yeterli. Plan öğünleri anahtar olmadan çalışır.',
  'Add key': 'Anahtar ekle',
  'Add to Home Screen': 'Ana Ekrana ekle',
  'Use “Add to Home Screen” in the browser’s Share menu. Data is kept more reliably that way.': 'Tarayıcının Paylaş menüsünde “Ana Ekrana Ekle” seçeneğini kullan. Veriler bu şekilde daha güvenle saklanır.',
  'Good things take time': 'Güzel şeyler zaman alır',
  'Getting started, step {n} of 4': 'Başlangıç, adım {n}/4',
  Done: 'Tamam',
  Hide: 'Gizle',

  // ——— js/views.js: Today, day header and the weigh-in and steps sheets ———
  Today: 'Bugün',
  '{date} · day {n}': '{date} · {n}. gün',
  'Back to today': 'Bugüne dön',
  'Today’s weigh-in': 'Bugünkü tartım',
  'Weigh-in for {date}': 'Tartım: {date}',
  'Today’s steps': 'Bugünkü adımlar',
  'Steps for {date}': 'Adımlar: {date}',
  Cancel: 'Vazgeç',
  'Weigh in the morning under the same conditions. A single day fluctuates; the maths uses the 7-day average.': 'Sabahları aynı koşullarda tartıl. Tek bir gün dalgalanır; hesaplar 7 günlük ortalamayı kullanır.',
  'Your daily step count from the phone’s Health app. Goal {goal}.': 'Telefonundaki Sağlık uygulamasından günlük adım sayın. Hedef {goal}.',
  steps: 'adım',
  'Remove weigh-in': 'Tartımı kaldır',
  'Remove steps': 'Adımları kaldır',

  // ——— js/views.js: entry sheet ———
  'from photo': 'fotoğraftan',
  'from file': 'dosyadan',
  edited: 'düzenlendi',
  out: 'dışarıda',
  'at {place}': '{place} konumunda',
  Delete: 'Sil',
  'Photo of the meal': 'Öğünün fotoğrafı',
  'Waiting for analysis.': 'Analiz bekleniyor.',
  Analyse: 'Analiz et',
  'Try again': 'Tekrar dene',
  'Off plan': 'Plan dışı',
  'Weekly extra': 'Haftalık ekstra',
  'Plan meal': 'Plan öğünü',
  'Your edit': 'Düzenlemen',
  'Not itemised': 'Kalemlere ayrılmadı',
  Item: 'Kalem',
  Amount: 'Miktar',
  'Something the photo does not show?': 'Fotoğrafın göstermediği bir şey mi var?',
  'Something to correct?': 'Düzeltilecek bir şey mi var?',
  'Answer briefly': 'Kısaca yanıtla',
  'e.g. 2 eggs, low-fat cheese, baked': 'örn. 2 yumurta, az yağlı peynir, fırında',
  Update: 'Güncelle',
  'The model revises the items with your note.': 'Model kalemleri notunla yeniden düzenler.',
  '{p} g protein, {c} g carbs, {f} g fat': '{p} g protein, {c} g karbonhidrat, {f} g yağ',
  'Rough estimate. A short note below tightens it.': 'Kaba tahmin. Aşağıya kısa bir not yazarsan daha kesin olur.',
  Portion: 'Porsiyon',
  'Protein (g)': 'Protein (g)',
  Time: 'Saat',
  'Save changes': 'Değişiklikleri kaydet',
  'Add to favourites': 'Favorilere ekle',
  'Analyse again': 'Tekrar analiz et',
  'Analyse again with Sonnet': 'Sonnet ile tekrar analiz et',
  'Note: {text}': 'Not: {text}',
  Entry: 'Kayıt',
  'Step count': 'Adım sayısı',
  '{mult} portion': '{mult} porsiyon',
  'off plan': 'plan dışı',
  'weekly extra': 'haftalık ekstra',
  'plan meal': 'plan öğünü',
  'has a question': 'bir sorusu var',
  'rough estimate': 'kaba tahmin',

  // ——— js/views.js: Log ———
  'Writing the review…': 'Değerlendirme yazılıyor…',
  Helped: 'İşe yarayanlar',
  'Cost most': 'En çok kaloriye mal olanlar',
  Next: 'Sonraki adım',
  'Written before the day ended.': 'Gün bitmeden yazıldı.',
  'The log changed after this review.': 'Günlük bu değerlendirmeden sonra değişti.',
  'AI review, {when}.': 'Yapay zekâ değerlendirmesi, {when}.',
  'Update the review': 'Değerlendirmeyi güncelle',
  'Review again': 'Tekrar değerlendir',
  'Review the day so far': 'Günü şu ana kadar değerlendir',
  'Review this day': 'Bu günü değerlendir',
  Yesterday: 'Dün',
  '<b>{kcal}</b> / {target} kcal, {p} g protein': '<b>{kcal}</b> / {target} kcal, {p} g protein',
  'Photo and free-text analysis needs an API key. Plan meals, weight and steps work without one.': 'Fotoğraf ve serbest metin analizi için API anahtarı gerekir. Plan öğünleri, kilo ve adımlar anahtarsız çalışır.',
  '{n} entry is waiting for analysis.|{n} entries are waiting for analysis.': '{n} kayıt analiz bekliyor.',
  'Analyse all': 'Hepsini analiz et',
  Log: 'Günlük',
  'Everything you sent, newest first, with a review of each day. Tap an entry to correct it.': 'Gönderdiğin her şey, en yenisi en üstte, her günün değerlendirmesiyle birlikte. Düzeltmek için bir kayda dokun.',
  'Nothing logged yet.': 'Henüz bir şey kaydedilmedi.',
  'Everything you send lands here: photos, meals you type, weigh-ins, steps.': 'Gönderdiğin her şey burada toplanır: fotoğraflar, yazdığın öğünler, tartımlar, adımlar.',
  'Choose from library': 'Fotoğraf kitaplığından seç',
  'Typing works too. Tap the box below to see examples.': 'Yazarak da olur. Örnekler için aşağıdaki kutuya dokun.',

  // ——— js/views.js: Check ———
  'Good choice': 'İyi seçim',
  'With care': 'Dikkatle',
  'Leave it': 'Bırak',
  Menu: 'Menü',
  Product: 'Ürün',
  Dish: 'Yemek',
  '<b>{kcal}</b> kcal, {p} g protein': '<b>{kcal}</b> kcal, {p} g protein',
  '<b>{kcal}</b> kcal': '<b>{kcal}</b> kcal',
  'Leaves {kcal} kcal of today’s budget.': 'Bugünün bütçesinde {kcal} kcal kalır.',
  '{kcal} kcal more than is left today.': 'Bugün kalandan {kcal} kcal fazla.',
  'Today’s budget is already used up.': 'Bugünün bütçesi zaten doldu.',
  'Quality {n} of 5': 'Kalite {n}/5',
  Quality: 'Kalite',
  Instead: 'Onun yerine',
  'Order it like this': 'Şöyle sipariş et',
  'Make it fit': 'Uygun hale getir',
  'Log this': 'Bunu kaydet',
  Verdict: 'Sonuç',
  Check: 'Kontrol',
  'Your note: {note}': 'Notun: {note}',
  'From {n} photo; the photos were not kept. Numbers are estimates.|From {n} photos; the photos were not kept. Numbers are estimates.': '{n} fotoğraftan; fotoğraflar saklanmadı. Sayılar tahmindir.',
  'From your note; the photos were not kept. Numbers are estimates.': 'Notundan; fotoğraflar saklanmadı. Sayılar tahmindir.',
  'Remove this check': 'Bu kontrolü kaldır',
  'Photo {n} for this check': 'Bu kontrol için {n}. fotoğraf',
  'Remove photo {n}': '{n}. fotoğrafı kaldır',
  'A check is done by a model, so it needs an API key.': 'Kontrolü bir model yapar, bu yüzden API anahtarı gerekir.',
  'Other checks': 'Diğer kontroller',
  'Earlier checks': 'Önceki kontroller',
  '{kind}, {verdict}: {name}': '{kind}, {verdict}: {name}',
  leave: 'bırak',
  best: 'en iyisi',
  'with care': 'dikkatle',
  'Before you order or buy: photograph the menu, the dish or the product and get a verdict against your plan.': 'Sipariş vermeden ya da satın almadan önce: menünün, yemeğin ya da ürünün fotoğrafını çek ve planına göre bir sonuç al.',
  'New check': 'Yeni kontrol',
  'Left today: <b>{kcal}</b> kcal, <b>{p}</b> g protein to go.': 'Bugün kalan: <b>{kcal}</b> kcal; <b>{p}</b> g protein daha lazım.',
  'Left today: <b>{kcal}</b> kcal.': 'Bugün kalan: <b>{kcal}</b> kcal.',
  'Today’s budget is used up, by <b>{kcal}</b> kcal.': 'Bugünün bütçesi doldu, <b>{kcal}</b> kcal aşıldı.',
  'Today’s budget is used up.': 'Bugünün bütçesi doldu.',
  'Choose photos': 'Fotoğraf seç',
  '{n} of {max} photos.': '{n}/{max} fotoğraf.',
  'Up to {max} photos: both pages of a menu, or the front and the nutrition table of a product.': 'En fazla {max} fotoğraf: menünün iki sayfası ya da ürünün ön yüzü ve besin değerleri tablosu.',
  'They are sent for this check and not kept.': 'Bu kontrol için gönderilir, saklanmaz.',
  'A note for this check': 'Bu kontrol için not',
  'Add a note: “dinner, very hungry”': 'Not ekle: “akşam yemeği, çok açım”',
  'Check against my plan': 'Planıma göre kontrol et',
  'What a check tells you': 'Kontrol sana ne söyler',
  'How good the food is in general, whether it fits your plan and what is left of today, and how to order it so that it does.': 'Yemeğin genel olarak ne kadar iyi olduğunu, planına ve bugünden kalana uyup uymadığını ve uyması için nasıl sipariş etmen gerektiğini.',
  'It works for a restaurant menu, a dish in front of you, a product on the shelf, or two products side by side.': 'Restoran menüsü, önündeki bir yemek, raftaki bir ürün ya da yan yana iki ürün için çalışır.',

  // ——— js/views.js: Progress ———
  'You {kg}': 'Sen {kg}',
  '{date} at this pace': 'Bu hızla {date}',
  'Line {kg}': 'Çizgi {kg}',
  'Weight over the whole plan: 7-day average {avg} kg, your line {line} kg, at this pace you arrive on {date}.': 'Tüm plan boyunca kilo: 7 günlük ortalama {avg} kg, çizgin {line} kg, bu hızla {date} tarihinde varıyorsun.',
  'Weight over the whole plan: 7-day average {avg} kg, your line {line} kg.': 'Tüm plan boyunca kilo: 7 günlük ortalama {avg} kg, çizgin {line} kg.',
  'Weight over the last 7 days: 7-day average {avg} kg, your line {line} kg.': 'Son 7 günde kilo: 7 günlük ortalama {avg} kg, çizgin {line} kg.',
  'Weight over the last two weeks: 7-day average {avg} kg, your line {line} kg.': 'Son iki haftada kilo: 7 günlük ortalama {avg} kg, çizgin {line} kg.',
  'Weight chart: no weigh-ins yet.': 'Kilo grafiği: henüz tartım yok.',
  'Weight chart: no weigh-ins in the last 7 days.': 'Kilo grafiği: son 7 günde tartım yok.',
  'Weight chart: no weigh-ins in the last two weeks.': 'Kilo grafiği: son iki haftada tartım yok.',
  'Chart range': 'Grafik aralığı',
  Week: 'Hafta',
  '2 weeks': '2 hafta',
  Overall: 'Tümü',
  'No weigh-ins in the last 7 days.': 'Son 7 günde tartım yok.',
  'No weigh-ins in the last two weeks.': 'Son iki haftada tartım yok.',
  'You (7-day average)': 'Sen (7 günlük ortalama)',
  'Your line': 'Çizgin',
  'Daily weigh-in': 'Günlük tartım',
  'At this pace': 'Bu hızla',
  'weigh-in': 'tartım',
  average: 'ortalama',
  line: 'çizgi',
  'target reached': 'hedefe ulaşıldı',
  'minimum reached': 'minimuma ulaşıldı',
  'nearly at the minimum': 'minimuma yakın',
  'short of the minimum': 'minimumun altında',
  '{date}: nothing logged': '{date}: kayıt yok',
  '{date}: {kcal} of {target} kcal, {status}; protein {p} g, {level}': '{date}: {kcal} / {target} kcal, {status}; protein {p} g, {level}',
  'This week so far': 'Bu hafta şu ana kadar',
  '{n} of 7 days on plan, protein reached on {p}.': 'Planda geçen gün: {n}/7, protein hedefine ulaşılan gün: {p}.',
  '{n} day on plan so far. Keep going, the week is still yours.|{n} days on plan so far. Keep going, the week is still yours.': 'Şimdiye kadar {n} gün planda. Devam et, hafta hâlâ senin.',
  'Budget <b>{rest}</b> rest · <b>{train}</b> workout': 'Bütçe: dinlenme <b>{rest}</b> · antrenman <b>{train}</b>',
  'Min <b>{kcal}</b> kcal': 'En az <b>{kcal}</b> kcal',
  'Protein <b>{goal} g</b> · min <b>{min} g</b>': 'Protein <b>{goal} g</b> · en az <b>{min} g</b>',
  'How to read a day': 'Bir gün nasıl okunur',
  over: 'üstünde',
  'far over': 'çok üstünde',
  'under {kcal}': '{kcal} altı',
  today: 'bugün',
  '{n} g target': 'hedef {n} g',
  '{n} g minimum': 'minimum {n} g',
  nearly: 'neredeyse',
  short: 'eksik',
  'Protein never breaks a streak. A "+" after the calories means a little over the budget, still within the {pct}% margin.': 'Protein bir seriyi asla bozmaz. Kalorilerden sonraki “+”, bütçenin biraz aşıldığını ama %{pct} payın içinde kaldığını gösterir.',
  '{n} day on plan so far, {left} to go. Keep going, the week is still yours.|{n} days on plan so far, {left} to go. Keep going, the week is still yours.': 'Şimdiye kadar {n} gün planda, {left} kaldı. Devam et, hafta hâlâ senin.',
  'Over the budget': 'Bütçenin üstünde',
  'Well over the budget': 'Bütçenin çok üstünde',
  'Under the minimum': 'Minimumun altında',
  'On plan.': 'Planda.',
  'Still in progress.': 'Hâlâ devam ediyor.',
  '{verdict}: {reasons}.': '{verdict}: {reasons}.',
  '{verdict}.': '{verdict}.',
  'Also: {notes}.': 'Ayrıca: {notes}.',
  '{kcal} / {target} kcal, {p} g protein ({level}), weigh-in {kg} kg.': '{kcal} / {target} kcal, {p} g protein ({level}), tartım {kg} kg.',
  'no meals logged, weigh-in {kg} kg.': 'öğün kaydı yok, tartım {kg} kg.',
  '{kcal} / {target} kcal, {p} g protein ({level}).': '{kcal} / {target} kcal, {p} g protein ({level}).',
  'no meals logged.': 'öğün kaydı yok.',
  'Open day': 'Günü aç',
  Date: 'Tarih',
  'Your average': 'Ortalaman',
  'Your average has been more than 0.7 kg behind schedule for two weeks. Cut 100 kcal a day or add 2,000 steps. Do not go below {kcal} kcal.': 'Ortalaman iki haftadır programın 0,7 kg’dan fazla gerisinde. Günde 100 kcal azalt ya da 2.000 adım ekle. Alt sınır {kcal} kcal: bunun altına inme.',
  'Open goals': 'Hedefleri aç',
  'At this pace you arrive on <b>{date}</b>, {days} early.': 'Bu hızla <b>{date}</b> tarihinde varırsın, {days} erken.',
  'At this pace you arrive on <b>{date}</b>, {days} after the goal date.': 'Bu hızla <b>{date}</b> tarihinde varırsın, hedef tarihten {days} sonra.',
  'At this pace you arrive on <b>{date}</b>, right on the date.': 'Bu hızla <b>{date}</b> tarihinde varırsın, tam zamanında.',
  Progress: 'İlerleme',
  Lost: 'Verilen kilo',
  'To go': 'Kalan',
  'Per week': 'Haftalık',
  'Arrival at this pace': 'Bu hızla varış',
  'The weekly rate and the arrival appear after 4 weigh-ins within the last 14 days, at least 6 days apart.': 'Haftalık hız ve varış tarihi, son 14 gün içinde en az 6 gün arayla yapılmış 4 tartımdan sonra görünür.',
  'Consistency calendar': 'Düzen takvimi',
  '{days} on plan in a row.': '{days} art arda planda.',
  'Days on plan build a run.': 'Planda geçen günler seri oluşturur.',
  Checkpoints: 'Kilometre taşları',
  'Weigh-in table': 'Tartım tablosu',
  Day: 'Gün',
  Avg: 'Ort.',
  Line: 'Çizgi',
  'No weigh-ins yet. Enter one on Today, or type a number into the log.': 'Henüz tartım yok. Bugün ekranından bir tane gir ya da günlüğe bir sayı yaz.',
  'Every kilo collected.': 'Her kilo toplandı.',
  'Next kilo at <b>{kg}</b>, {away} kg away.': 'Sıradaki kilo: <b>{kg}</b>, {away} kg uzakta.',
  'A kilo is yours when a weigh-in reaches it.': 'Bir tartım o kiloya ulaşınca o kilo senindir.',
  'The beam · latest weigh-in': 'Çubuk · son tartım',
  '{got} of {n} kilo|{got} of {n} kilos': 'Kilo: {got}/{n}',
  'day|days': 'gün',
  'Days on plan': 'Planda geçen günler',
  'In a row': 'Art arda',
  'Longest run': 'En uzun seri',
  'On plan': 'Planda',
  'All 5 goals': '5 hedefin hepsi',

  // ——— js/views.js: Plan ———
  '{meal}, {kcal} kcal, {p} g protein. Details': '{meal}, {kcal} kcal, {p} g protein. Ayrıntılar',
  'Add photo': 'Fotoğraf ekle',
  Plan: 'Plan',
  '{n} of {total} meals show your own photo.': 'Kendi fotoğrafın olan öğün: {n}/{total}.',
  'Tap a meal for its ingredients, and to add a photo of your own plate.': 'Malzemeleri görmek ve kendi tabağının fotoğrafını eklemek için bir öğüne dokun.',
  'Daily goals': 'Günlük hedefler',
  'Rest day <b>{kcal}</b> kcal': 'Dinlenme günü <b>{kcal}</b> kcal',
  'Workout day <b>{kcal}</b> kcal': 'Antrenman günü <b>{kcal}</b> kcal',
  'Protein <b>{n}</b> g': 'Protein: <b>{n}</b> g',
  'Fibre <b>{n}</b> g': 'Lif: <b>{n}</b> g',
  'The first meal of the day.': 'Günün ilk öğünü.',
  'A protein snack: 250 g of skyr.': 'Protein ara öğünü: 250 g skyr.',
  'On meatball or salmon days, cottage cheese tops up the protein.': 'Köfte ya da somon günlerinde lor peyniri proteini tamamlar.',
  'Meat, chicken and fish by raw weight.': 'Et, tavuk ve balık çiğ ağırlıkla.',
  'Workout-day extras': 'Antrenman günü ekstraları',
  'Only on workout days; together about 200 kcal.': 'Sadece antrenman günlerinde; toplam yaklaşık 200 kcal.',
  'Herbal tea by default.': 'Varsayılan olarak bitki çayı.',
  'The rules': 'Kurallar',
  'Dinner rotation': 'Akşam yemeği döngüsü',
  'Fish twice and legumes twice a week.': 'Haftada iki kez balık, iki kez baklagil.',
  'Every day': 'Her gün',
  'The week’s extras': 'Haftanın ekstraları',
  'Off for the whole period': 'Tüm dönem boyunca yok',
  'Training and movement': 'Antrenman ve hareket',
  Process: 'Süreç',
  'Frame the picture': 'Resmi çerçevele',
  '{meal}. Drag until the plate sits in the circle, zoom until it fills it.': '{meal}. Tabak çemberin içine gelene kadar sürükle, çemberi dolduruncaya kadar yakınlaştır.',
  'Preview of the picture. Drag to move.': 'Resmin önizlemesi. Taşımak için sürükle.',
  Zoom: 'Yakınlaştır',
  'Light and colour are evened out so all plan pictures match. Only this framed picture is stored, not the original photo.': 'Tüm plan resimleri uyumlu olsun diye ışık ve renk dengelenir. Yalnızca bu çerçevelenmiş resim saklanır, orijinal fotoğraf değil.',
  'Use this picture': 'Bu resmi kullan',
  'No photo yet. Take one the next time you make this.': 'Henüz fotoğraf yok. Bunu bir dahaki sefere yaptığında bir tane çek.',
  Retake: 'Yeniden çek',
  'Choose a photo': 'Fotoğraf seç',
  'Remove photo': 'Fotoğrafı kaldır',
  '{p} g protein, {c} g carbs, {f} g fat, {fib} g fibre': '{p} g protein, {c} g karbonhidrat, {f} g yağ, {fib} g lif',
  'Log for today': 'Bugüne kaydet',

  // ——— js/views.js: Settings ———
  'No backup yet': 'Henüz yedek yok',
  'Last backup today': 'Son yedek bugün',
  'Last backup {n} day ago|Last backup {n} days ago': 'Son yedek {n} gün önce',
  'No key': 'Anahtar yok',
  'Analysis goes straight from this phone to the provider you choose. The key is stored only on this device and is never written to a backup.': 'Analiz doğrudan bu telefondan seçtiğin sağlayıcıya gider. Anahtar yalnızca bu cihazda saklanır ve yedeğe asla yazılmaz.',
  Provider: 'Sağlayıcı',
  'Gemini, OpenCode, OpenRouter (OpenAI-compatible)': 'Gemini, OpenCode, OpenRouter (OpenAI uyumlu)',
  'Claude (needs prepaid credit)': 'Claude (ön ödemeli bakiye gerekir)',
  Preset: 'Hazır ayar',
  'Choose, or fill in the fields below': 'Seç ya da aşağıdaki alanları doldur',
  Key: 'Anahtar',
  'Get a free key at aistudio.google.com with “Get API key”.': 'aistudio.google.com adresinde “Get API key” ile ücretsiz anahtar al.',
  Model: 'Model',
  'model id': 'model kimliği',
  Address: 'Adres',
  'Save and test': 'Kaydet ve test et',
  'Save only': 'Yalnızca kaydet',
  'If the model does not read photos: {find}. It tries the provider’s models one by one with a small test image.': 'Model fotoğraf okumuyorsa: {find}. Sağlayıcının modellerini küçük bir test görseliyle tek tek dener.',
  'find a model that reads photos': 'fotoğraf okuyan bir model bul',
  'Review each finished day by itself': 'Biten her günü kendiliğinden değerlendir',
  'One short text request a day, sent when you open the app: the day’s meals and numbers, no photos. Switched off, a review is written only when you ask for it in the Log.': 'Uygulamayı açtığında günde bir kısa metin isteği gönderilir: günün öğünleri ve sayıları, fotoğraf yok. Kapalıyken değerlendirme yalnızca Günlük’te sen istediğinde yazılır.',
  'So far {calls} call, {input} input and {output} output tokens.|So far {calls} calls, {input} input and {output} output tokens.': 'Şimdiye kadar {calls} çağrı, {input} giriş ve {output} çıkış token’ı.',
  'Estimated cost {cost}.': 'Tahmini maliyet {cost}.',
  Start: 'Başlangıç',
  End: 'Bitiş',
  'Start weight': 'Başlangıç kilosu',
  'Goal weight': 'Hedef kilo',
  'Rest-day kcal': 'Dinlenme günü kcal',
  'Workout-day kcal': 'Antrenman günü kcal',
  'Minimum kcal': 'En düşük kcal',
  'Save goals': 'Hedefleri kaydet',
  'Use the photo’s location': 'Fotoğrafın konumunu kullan',
  'Location is read on the device and matched to your saved places here. The model only gets the word “Home”, “Office” or “out”; coordinates are never sent to the model (they are in your backup file). When you choose from the library, location only comes through if Location is switched on under Options in the picker.': 'Konum cihazda okunur ve burada kayıtlı yerlerinle eşleştirilir. Modele yalnızca “Home”, “Office” ya da “out” kelimesi gider; koordinatlar modele asla gönderilmez (yedek dosyanda bulunurlar). Kitaplıktan seçtiğinde konum, yalnızca seçicideki Seçenekler altında Konum açıksa gelir.',
  'I am here: Home': 'Buradayım: Ev',
  'I am here: Office': 'Buradayım: Ofis',
  'Saved places: {names}.': 'Kayıtlı yerler: {names}.',
  'No saved places.': 'Kayıtlı yer yok.',
  'Data lives only on this device. iOS can delete web data when storage runs low; save a backup to Files once a week.': 'Veriler yalnızca bu cihazda tutulur. Depolama azalınca iOS web verilerini silebilir; haftada bir yedeği Dosyalar’a kaydet.',
  'Save backup': 'Yedeği kaydet',
  'With photos': 'Fotoğraflarla',
  'Restore from backup': 'Yedekten geri yükle',
  'For analysis on a computer: one .sql file with your days, meals and goals that loads into any SQLite database. Photos, keys and saved places are left out.': 'Bilgisayarda analiz için: günlerini, öğünlerini ve hedeflerini içeren, her SQLite veritabanına yüklenebilen tek bir .sql dosyası. Fotoğraflar, anahtarlar ve kayıtlı yerler dahil değildir.',
  'Export for SQLite': 'SQLite için dışa aktar',
  'Persistent storage is on.': 'Kalıcı depolama açık.',
  'Persistent storage has not been granted yet. Adding the app to the Home Screen makes that more likely.': 'Kalıcı depolama henüz verilmedi. Uygulamayı Ana Ekran’a eklemek bunu daha olası kılar.',
  'Space used: {mb} MB.': 'Kullanılan alan: {mb} MB.',
  'Request persistent storage': 'Kalıcı depolama iste',
  Remove: 'Kaldır',
  'Open an entry and tap “Add to favourites”. It then logs with one tap from the Log tab.': 'Bir kaydı aç ve “Favorilere ekle” düğmesine dokun. Sonra Günlük sekmesinden tek dokunuşla kaydedilir.',
  'The vitamins and minerals you take every day. They appear as chips on Today, and a tap ticks one for the day, so you can see at a glance what you forgot. They are not part of the daily goals.': 'Her gün aldığın vitamin ve mineraller. Bugün ekranında çipler olarak görünürler; dokunmak o gün için birini işaretler, böylece neyi unuttuğunu bir bakışta görürsün. Günlük hedeflerin parçası değildirler.',
  Edit: 'Düzenle',
  'None yet.': 'Henüz yok.',
  Name: 'Ad',
  Magnesium: 'Magnezyum',
  'Dose (optional)': 'Doz (isteğe bağlı)',
  '400 mg': '400 mg',
  'Add supplement': 'Takviye ekle',
  'The app looks for a new version when it opens and when it comes to the front; if it finds one it reloads. Your entries are not affected.': 'Uygulama açılırken ve öne geldiğinde yeni sürüm arar; bulursa yeniden yüklenir. Kayıtların etkilenmez.',
  'Check for updates': 'Güncellemeleri denetle',
  'Clear cache and reload': 'Önbelleği temizle ve yenile',
  'Neither can be undone. {backup}': 'İkisi de geri alınamaz. {backup}',
  'Save a backup first': 'Önce bir yedek kaydet',
  'Clear my log': 'Günlüğümü temizle',
  'Starts your tracking over; the app stays set up as it is.': 'Takibini baştan başlatır; uygulama olduğu gibi kurulu kalır.',
  Deletes: 'Siler',
  'Meals and their photos, weigh-ins, steps, water, coffee, supplements taken, workout days, day reviews and Check verdicts.': 'Öğünler ve fotoğrafları, tartımlar, adımlar, su, kahve, alınan takviyeler, antrenman günleri, gün değerlendirmeleri ve Kontrol sonuçları.',
  Keeps: 'Korur',
  'Every setting: goals and dates, favourites, saved places, the plan’s pictures, your API key and provider, and the badges you have earned.': 'Tüm ayarlar: hedefler ve tarihler, favoriler, kayıtlı yerler, planın resimleri, API anahtarın ve sağlayıcın, bir de kazandığın rozetler.',
  'Factory reset': 'Fabrika ayarlarına sıfırla',
  'Back to how the app was on its first launch.': 'Uygulamayı ilk açıldığı haline döndürür.',
  'Everything above, plus your goals and dates, favourites, saved places, the plan’s pictures, the usage totals and your other settings. The getting-started steps come back.': 'Yukarıdakilerin hepsi, ayrıca hedeflerin ve tarihlerin, favorilerin, kayıtlı yerlerin, planın resimleri, kullanım toplamları ve diğer ayarların. Başlangıç adımları geri gelir.',
  'Nothing, except your API key and provider if the box is ticked.': 'Hiçbir şey; yalnızca kutu işaretliyse API anahtarın ve sağlayıcın kalır.',
  'Keep my API key and provider': 'API anahtarımı ve sağlayıcımı koru',
  'You will be asked to type {word}.': 'Senden {word} yazman istenecek.',
  Language: 'Dil',
  'The change applies at once. Your entries are not changed.': 'Değişiklik hemen uygulanır. Kayıtların değişmez.',
  'Photo and text analysis': 'Fotoğraf ve metin analizi',
  Goals: 'Hedefler',
  '{start} kg to {end} kg by {date}': '{start} kg → {end} kg, {date}',
  'Backup and export': 'Yedekleme ve dışa aktarma',
  Location: 'Konum',
  'On: {names}': 'Açık: {names}',
  'On, no saved places': 'Açık, kayıtlı yer yok',
  Off: 'Kapalı',
  'None yet': 'Henüz yok',
  'Version and updates': 'Sürüm ve güncellemeler',
  'Version {v}': 'Sürüm {v}',
  Reset: 'Sıfırla',
  'Clear my log, or factory reset': 'Günlüğümü temizle ya da fabrika ayarlarına sıfırla',
  'Good things take time. A cucumber becomes a pickle through time and steady conditions, not one big effort, and that is what the app asks of you: a steady average along your line, day after day.': 'Güzel şeyler zaman alır. Salatalık turşuya zaman ve sabit koşullarla dönüşür, tek büyük bir çabayla değil; uygulama da senden bunu ister: gün be gün, çizgin boyunca istikrarlı bir ortalama.',
  'Entries, photos and settings are stored on this device. Photos and text you send for analysis go to the provider you chose.': 'Kayıtlar, fotoğraflar ve ayarlar bu cihazda saklanır. Analiz için gönderdiğin fotoğraflar ve metinler seçtiğin sağlayıcıya gider.',

  // ——— js/app.js: toasts, errors and sheets ———
  'Could not load that language. Try again when you are online.': 'Bu dil yüklenemedi. İnternete bağlanınca tekrar dene.',
  '{msg}. {label} is available.': '{msg}. Seçenek: {label}.',
  '{name} logged': '{name} kaydedildi',
  Undo: 'Geri al',
  'Entry deleted': 'Kayıt silindi',
  '{title} saved': '{title} kaydedildi',
  '{ml} ml of water added': '{ml} ml su eklendi',
  'Today is a workout day: budget {kcal} kcal': 'Bugün antrenman günü: bütçe {kcal} kcal',
  'Coffee is at the day’s maximum': 'Kahve günlük üst sınırda',
  'A coffee added': 'Bir kahve eklendi',
  '{n} coffees added': '{n} kahve eklendi',
  '{n} beers logged': '{n} bira kaydedildi',
  'Preparing {n} photos': '{n} fotoğraf hazırlanıyor',
  'Preparing photo': 'Fotoğraf hazırlanıyor',
  'Could not open a photo: {name}': 'Bir fotoğraf açılamadı: {name}',
  'Model busy, trying {alt}': 'Model meşgul, {alt} deneniyor',
  'Quota reached, trying {alt}': 'Kota doldu, {alt} deneniyor',
  'Provider busy, retrying ({n}/{of})': 'Sağlayıcı meşgul, yeniden deneniyor ({n}/{of})',
  'Add an API key in Settings to get a review.': 'Değerlendirme almak için Ayarlar’dan bir API anahtarı ekle.',
  'Add an API key in Settings to get a note.': 'Not almak için Ayarlar’dan bir API anahtarı ekle.',
  'Add an API key in Settings to get a check.': 'Kontrol yaptırmak için Ayarlar’dan bir API anahtarı ekle.',
  'Add an API key in Settings to get a new estimate.': 'Yeni tahmin almak için Ayarlar’dan bir API anahtarı ekle.',
  'The review failed. {detail}': 'Değerlendirme başarısız oldu. {detail}',
  'The note failed. {detail}': 'Not alınamadı. {detail}',
  'The check failed. {detail}': 'Kontrol başarısız oldu. {detail}',
  'The new estimate failed. {detail}': 'Yeni tahmin başarısız oldu. {detail}',
  'The model sent nothing usable. Try again.': 'Model kullanılabilir bir şey göndermedi. Tekrar dene.',
  'Try again when you are online.': 'İnternete bağlanınca tekrar dene.',
  'Try again a little later.': 'Biraz sonra tekrar dene.',
  'Could not open that photo': 'Fotoğraf açılamadı',
  'A check takes up to {n} photos': 'Bir kontrol en fazla {n} fotoğraf alır',
  'Nothing to judge was found. Try a closer or sharper photo.': 'Değerlendirilecek bir şey bulunamadı. Daha yakın veya daha net bir fotoğraf dene.',
  'Could not save the picture': 'Resim kaydedilemedi',
  'Picture saved': 'Resim kaydedildi',
  'Nothing to log was found in that, so the entry is unchanged.': 'Bunda kaydedilecek bir şey bulunamadı, kayıt değişmedi.',
  'Nothing to log was found: no food, weight or step count.': 'Kaydedilecek bir şey bulunamadı: yemek, kilo ya da adım sayısı yok.',
  'Analysis failed.': 'Analiz başarısız oldu.',
  'The file is ready': 'Dosya hazır',
  Save: 'Kaydet',
  'Backup ready': 'Yedek hazır',
  'Exported {days} and {meals}': 'Dışa aktarıldı: {days} ve {meals}',
  '{n} day|{n} days': '{n} gün',
  '{n} meal|{n} meals': '{n} öğün',
  'Could not read the file': 'Dosya okunamadı',
  'The backup could not be restored completely': 'Yedek tam olarak geri yüklenemedi',
  '{n} entry restored|{n} entries restored': '{n} kayıt geri yüklendi',
  '{restored}; {skipped}': '{restored}; {skipped}',
  '{n} damaged item skipped|{n} damaged items skipped': '{n} bozuk öğe atlandı',
  'First kilo down': 'İlk kilo verildi',
  '{n} kilos down': '{n} kilo verildi',
  'All five goals done today': 'Bugün beş hedefin hepsi tamam',
  Favourites: 'Favoriler',
  'Weight removed': 'Kilo kaldırıldı',
  'Steps removed': 'Adımlar kaldırıldı',
  'A glass of water added': 'Bir bardak su eklendi',
  'Give the supplement a name': 'Takviyeye bir ad ver',
  'At most {n} supplements': 'En fazla {n} takviye olabilir',
  'Already in the list': 'Zaten listede',
  'Remove {name}? Its history is no longer shown.': '{name} kaldırılsın mı? Geçmişi artık gösterilmez.',
  'Already in favourites': 'Zaten favorilerde',
  'Added to favourites. One tap next time.': 'Favorilere eklendi. Bir dahaki sefere tek dokunuş.',
  'Entry updated': 'Kayıt güncellendi',
  'The address must start with https://': 'Adres https:// ile başlamalı',
  'Saved on this device': 'Bu cihaza kaydedildi',
  'Key removed': 'Anahtar kaldırıldı',
  'Address, model and key are all required.': 'Adres, model ve anahtar gerekli.',
  'A key is required.': 'Anahtar gerekli.',
  'Your plan and limits: aistudio.google.com/rate-limit': 'Planın ve limitlerin: aistudio.google.com/rate-limit',
  'The provider said: “{detail}”': 'Sağlayıcının yanıtı: “{detail}”',
  'Failed.': 'Başarısız.',
  'Testing text…': 'Metin test ediliyor…',
  'Text works: “{title}”, {kcal} kcal ({tokensIn} input and {tokensOut} output tokens).': 'Metin çalışıyor: “{title}”, {kcal} kcal ({tokensIn} giriş ve {tokensOut} çıkış token’ı).',
  '{from}: {reason}\nSwitched to {model}. {line}': '{from}: {reason}\nYeni model: {model}. {line}',
  '{from}: {reason}\nFor now {model} answers instead. {line}': '{from}: {reason}\nŞimdilik şu model yanıt veriyor: {model}. {line}',
  'Text: {why}': 'Metin: {why}',
  'Testing photo…': 'Fotoğraf test ediliyor…',
  'Photos work: the model read the number in the test image.': 'Fotoğraflar çalışıyor: model test görselindeki sayıyı okudu.',
  'Photos do not work: the model could not read the test image. Pick a model with image support.': 'Fotoğraflar çalışmıyor: model test görselini okuyamadı. Görsel destekleyen bir model seç.',
  'Photo: {why}': 'Fotoğraf: {why}',
  'Enter the address and key first.': 'Önce adresi ve anahtarı gir.',
  'Fetching the model list…': 'Model listesi alınıyor…',
  'Could not fetch the model list. Type a model name and tap “Save and test”.': 'Model listesi alınamadı. Bir model adı yaz, sonra “Kaydet ve test et” düğmesine dokun.',
  '{id}: testing…': '{id}: test ediliyor…',
  '{id}: read the photo': '{id}: fotoğrafı okudu',
  '{id}: could not read the photo': '{id}: fotoğrafı okuyamadı',
  '{id}: {label}': '{id}: {label}',
  error: 'hata',
  'Selected model: {model}. Now tap “Save and test”.': 'Seçilen model: {model}. Şimdi “Kaydet ve test et” düğmesine dokun.',
  'No model that reads photos was found.': 'Fotoğraf okuyan bir model bulunamadı.',
  'Check the values: the end must be after the start, the goal weight below the start weight, and calories at least {kcal}, as the plan\'s rules say': 'Değerleri kontrol et: bitiş başlangıçtan sonra olmalı, hedef kilo başlangıç kilosunun altında olmalı ve planın kurallarına göre kalori en az {kcal} olmalı',
  'Goals saved': 'Hedefler kaydedildi',
  'Add an API key in Settings to get a note': 'Not almak için Ayarlar’dan bir API anahtarı ekle',
  'No connection. Try again when you are online': 'Bağlantı yok. İnternete bağlanınca tekrar dene',
  'Add an API key in Settings to get a review': 'Değerlendirme almak için Ayarlar’dan bir API anahtarı ekle',
  'Getting your location…': 'Konumun alınıyor…',
  'Could not get a location. Check that the browser has location permission.': 'Konum alınamadı. Tarayıcıda konum izni olduğundan emin ol.',
  'This spot is saved as “{name}”': 'Bu yer “{name}” olarak kaydedildi',
  'Offline caching is off in this browser; reloading the page is enough.': 'Bu tarayıcıda çevrimdışı önbellek kapalı; sayfayı yenilemen yeterli.',
  'Checking…': 'Kontrol ediliyor…',
  'Installing the new version…': 'Yeni sürüm yükleniyor…',
  'Up to date: this is the latest version.': 'Güncel: bu en son sürüm.',
  'Could not check. Check your internet connection.': 'Kontrol edilemedi. İnternet bağlantını kontrol et.',
  'Something is still being analysed. Try again in a moment': 'Bir şey hâlâ analiz ediliyor. Birazdan tekrar dene',
  'Clear your log? This deletes meals and their photos, weigh-ins, steps, water, coffee, supplements taken, workout days, day reviews and Check verdicts from this device. Your goals, favourites, saved places, plan pictures and API key stay, and so do the badges you have earned. It cannot be undone. Do you have a backup?': 'Günlüğün temizlensin mi? Bu cihazdan öğünler ve fotoğrafları, tartımlar, adımlar, su, kahve, alınan takviyeler, antrenman günleri, gün değerlendirmeleri ve Kontrol sonuçları silinir. Hedeflerin, favorilerin, kayıtlı yerlerin, planın resimleri, API anahtarın ve kazandığın rozetler kalır. Geri alınamaz. Yedeğin var mı?',
  'Log cleared': 'Günlük temizlendi',
  'reset.word': 'SİL', // the word to type for a factory reset; js/app.js accepts DELETE as well
  'Factory reset: this deletes everything on this device: your log and photos, goals, favourites, saved places, the plan’s pictures and the usage totals. {keyNote} It cannot be undone. Do you have a backup?\n\nType {word} to continue.': 'Fabrika ayarlarına sıfırlama: bu cihazdaki her şey silinir: günlüğün ve fotoğrafların, hedeflerin, favorilerin, kayıtlı yerlerin, planın resimleri ve kullanım toplamları. {keyNote} Geri alınamaz. Yedeğin var mı?\n\nDevam etmek için {word} yaz.',
  'Your API key and provider stay.': 'API anahtarın ve sağlayıcın kalır.',
  'Your API key and provider are deleted too.': 'API anahtarın ve sağlayıcın da silinir.',
  'Factory reset done. Your API key is kept': 'Fabrika ayarlarına dönüldü. API anahtarın korundu',
  'Factory reset done': 'Fabrika ayarlarına dönüldü',
  'Could not save: {reason}': 'Kaydedilemedi: {reason}',
  'storage error': 'depolama hatası',
  'Enter a value between 50 and 160 kg. Example: 85.4': 'Kilonu 50 ile 160 kg arasında gir. Örnek: 85,4',
  'Enter the step count in digits. Example: 8200': 'Adım sayısını rakamla gir. Örnek: 8200',
  'A new version is ready': 'Yeni sürüm hazır',
  Reload: 'Yenile',
  'Could not open the database': 'Veritabanı açılamadı',
  'Local storage may be off in private browsing. Open the app in a normal window or add it to the Home Screen.': 'Gizli gezinmede yerel depolama kapalı olabilir. Uygulamayı normal bir pencerede aç ya da Ana Ekran’a ekle.',
  // ——— js/badges.js: badge names and what they ask for ———
  'First meal': 'İlk öğün',
  'Log your first meal.': 'İlk öğününü kaydet.',
  'First weigh-in': 'İlk tartım',
  'Log your first weigh-in.': 'İlk tartımını kaydet.',
  'First day on plan': 'Planda ilk gün',
  'Finish a day with your calories on plan.': 'Bir günü kalorilerin planda olacak şekilde bitir.',
  'Days on plan in total: {n}': 'Toplam planda geçen gün: {n}',
  'Longest run': 'En uzun seri',
  'Days on plan in a row, your best so far: {n}': 'Art arda planda geçen gün, şimdiye kadarki en iyin: {n}',
  'Strong weeks': 'Güçlü haftalar',
  'Finished weeks with at least 6 days on plan: {n}': 'En az 6 günü planda geçen tamamlanan hafta: {n}',
  Anniversary: 'Kilometre taşı',
  'Days since you started: {n}': 'Başlayalı geçen gün: {n}',
  'Fresh start': 'Yeni başlangıç',
  'Come back after a break or a rough week, and land a day on plan.': 'Bir aradan ya da zor bir haftadan sonra dön ve bir günü planda bitir.',
  'Perfect days': 'Kusursuz günler',
  'Days with every goal done: {n}': 'Tüm hedeflerin tamamlandığı gün: {n}',
  'Protein days': 'Protein günleri',
  'Days with your protein reached: {n}': 'Protein hedefine ulaşılan gün: {n}',
  'Active days': 'Hareketli günler',
  'Days with your steps goal met: {n}': 'Adım hedefine ulaşılan gün: {n}',
  'Protein week': 'Protein haftası',
  'Reach your protein on all 7 days of a week.': 'Bir haftanın 7 gününde de proteinine ulaş.',
  'Weigh-ins': 'Tartımlar',
  'Days with a weigh-in: {n}': 'Tartım yapılan gün: {n}',
  'Weigh-in week': 'Tartım haftası',
  'Weigh in on all 7 days of a week.': 'Bir haftanın 7 gününde de tart.',
  'Logging week': 'Kayıt haftası',
  'Log something on all 7 days of a week.': 'Bir haftanın 7 gününde de bir şey kaydet.',
  'Kilos down': 'Verilen kilolar',
  'Whole kilos down from your start: {n}': 'Başlangıçtan bu yana verilen tam kilo: {n}',
  Halfway: 'Yarı yol',
  'Reach the halfway point to your target weight.': 'Hedef kilonun yarısına ulaş.',
  'Goal reached': 'Hedefe ulaşıldı',
  'Reach your target weight.': 'Hedef kilona ulaş.',
  Consistency: 'Düzen',
  'Complete days': 'Tam günler',
  Habits: 'Alışkanlıklar',
  Bronze: 'Bronz',
  Silver: 'Gümüş',
  Gold: 'Altın',
  Platinum: 'Platin',
  Badges: 'Rozetler',
  '{n} of {total}': '{n} / {total}',
  '{cur} of {target} kg': '{cur} / {target} kg',
  '{cur} / {target}': '{cur} / {target}',
  Locked: 'Kilitli',
  'Not earned yet': 'Henüz kazanılmadı',
  '{finish}, earned {date}': '{finish}, {date} tarihinde kazanıldı',
  'Earned {date}': '{date} tarihinde kazanıldı',
  'Steps to earn': 'Kazanma adımları',
  'Next up': 'Sıradaki',
  New: 'Yeni',
  'New badge': 'Yeni rozet',
  View: 'Göster',
  '{n} new badge|{n} new badges': '{n} yeni rozet',
  '{names} and more': '{names} ve daha fazlası',
  '{n} badge from your history|{n} badges from your history': 'Geçmişinden {n} rozet',
  // ——— js/badges.js, js/views.js: the avatar ———
  Gherkin: 'Kornişon',
  Dill: 'Dereotlu',
  'Well-brined': 'Tam kıvamında',
  Calm: 'Sakin',
  Smile: 'Gülümseme',
  Cool: 'Havalı',
  'Star-eyed': 'Yıldız gözlü',
  None: 'Yok',
  Leaf: 'Yaprak',
  Cap: 'Şapka',
  Scarf: 'Atkı',
  Headband: 'Saç bandı',
  Crown: 'Taç',
  Growth: 'Büyüme',
  Face: 'Yüz',
  Accessory: 'Aksesuar',
  'Your pickle': 'Turşun',
  'Earn {name}: {n}': 'Kazan: {name} ({n})',
  'Earn {name}': 'Kazan: {name}',
  'Log a meal and your first badge is on its way.': 'Bir öğün kaydet, ilk rozetin yolda.',
  'Locked parts show what to earn. Nothing changes by itself.': 'Kilitli parçalar neyi kazanman gerektiğini gösterir. Kendiliğinden hiçbir şey değişmez.',
};
